# Generated by Django 4.0.3 on 2022-07-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_resize_recipe_servings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resize',
        ),
    ]
